name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        platform: ['x86_64', 'arm64']
        include:
          - platform: 'x86_64'
            docker-platform: 'linux/amd64'
          - platform: 'arm64'
            docker-platform: 'linux/arm64'
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercased repo name
      run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.REPO_NAME }}/python:${{ matrix.python-version }}-${{ matrix.platform }}
        build-args: |
          VERSION=${{ matrix.python-version }}
          PLATFORM=${{ matrix.platform }}
        file: ./docker/Dockerfile
        platforms: ${{ matrix.docker-platform }}

    - name: Image build complete
      run: echo "Image for Python ${{ matrix.python-version }} on ${{ matrix.platform }} built and pushed successfully."
